"""add_user_fields

Revision ID: 2bb9c6ce1cae
Revises: 43edbb529bc8
Create Date: 2026-02-23 16:38:54.292996
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bb9c6ce1cae'
down_revision: Union[str, None] = '43edbb529bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_predictions', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Loại vé: mega645, power655',
               existing_server_default=sa.text("'mega645'::character varying"))
    op.drop_index('idx_ai_predictions_type', table_name='ai_predictions')
    op.create_index(op.f('ix_ai_predictions_type'), 'ai_predictions', ['type'], unique=False)
    op.alter_column('draw_results', 'jackpot_value',
               existing_type=sa.BIGINT(),
               comment='Giá trị Jackpot 1 (VND)',
               existing_comment='Giá trị Jackpot (VND)',
               existing_nullable=True)
    op.alter_column('draw_results', 'jackpot2_value',
               existing_type=sa.BIGINT(),
               comment='Giá trị Jackpot 2 (VND)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'jackpot2_winners',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_draw_results_draw_period'), 'draw_results', ['draw_period'], unique=False)
    op.alter_column('number_stats', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Loại vé: mega645, power655',
               existing_server_default=sa.text("'mega645'::character varying"))
    op.alter_column('number_stats', 'max_gap',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Khoảng cách lớn nhất từng ghi nhận (kỳ)',
               existing_nullable=False)
    op.alter_column('number_stats', 'current_gap',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Khoảng cách hiện tại tính từ lần cuối xuất hiện (kỳ)',
               existing_nullable=False)
    op.drop_index('idx_number_stats_type', table_name='number_stats')
    op.create_index(op.f('ix_number_stats_number'), 'number_stats', ['number'], unique=False)
    op.create_index(op.f('ix_number_stats_type'), 'number_stats', ['type'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # Add is_active as nullable first
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Update existing users
    op.execute("UPDATE users SET is_active = true")
    # Set to NOT NULL
    op.alter_column('users', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_number_stats_type'), table_name='number_stats')
    op.drop_index(op.f('ix_number_stats_number'), table_name='number_stats')
    op.create_index('idx_number_stats_type', 'number_stats', ['type'], unique=False)
    op.alter_column('number_stats', 'current_gap',
               existing_type=sa.INTEGER(),
               comment='Khoảng cách hiện tại tính từ lần cuối xuất hiện (kỳ)',
               existing_nullable=False)
    op.alter_column('number_stats', 'max_gap',
               existing_type=sa.INTEGER(),
               comment='Khoảng cách lớn nhất từng ghi nhận (kỳ)',
               existing_nullable=False)
    op.alter_column('number_stats', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Loại vé: mega645, power655',
               existing_server_default=sa.text("'mega645'::character varying"))
    op.drop_index(op.f('ix_draw_results_draw_period'), table_name='draw_results')
    op.alter_column('draw_results', 'jackpot2_winners',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'jackpot2_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Giá trị Jackpot 2 (VND)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'jackpot_value',
               existing_type=sa.BIGINT(),
               comment='Giá trị Jackpot (VND)',
               existing_comment='Giá trị Jackpot 1 (VND)',
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_predictions_type'), table_name='ai_predictions')
    op.create_index('idx_ai_predictions_type', 'ai_predictions', ['type'], unique=False)
    op.alter_column('ai_predictions', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Loại vé: mega645, power655',
               existing_server_default=sa.text("'mega645'::character varying"))
    # ### end Alembic commands ###
