"""Add is_verified and matches to ai_predictions

Revision ID: 43edbb529bc8
Revises: c3e559dbd6be
Create Date: 2026-02-22 22:28:07.821344
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43edbb529bc8'
down_revision: Union[str, None] = 'c3e559dbd6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_predictions', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('ai_predictions', sa.Column('matches', sa.INTEGER(), nullable=True))
    op.alter_column('draw_results', 'jackpot_winners',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'first_prize_value',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'first_prize_winners',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'second_prize_value',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'second_prize_winners',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'third_prize_value',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'third_prize_winners',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('draw_results', 'third_prize_winners',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'third_prize_value',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'second_prize_winners',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'second_prize_value',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'first_prize_winners',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'first_prize_value',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('draw_results', 'jackpot_winners',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('ai_predictions', 'matches')
    op.drop_column('ai_predictions', 'is_verified')
    # ### end Alembic commands ###
