"""init_tables

Revision ID: c3e559dbd6be
Revises: 
Create Date: 2026-02-22 19:43:56.980904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c3e559dbd6be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_period', sa.String(length=20), nullable=False),
    sa.Column('predicted_numbers', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_premium_only', sa.Boolean(), nullable=False, comment='Chỉ user Premium mới xem được'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_target_period'), 'ai_predictions', ['target_period'], unique=False)
    op.create_table('draw_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('draw_period', sa.String(length=20), nullable=False),
    sa.Column('numbers', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Loại vé: mega645, power655, max3d...'),
    sa.Column('jackpot_won', sa.Boolean(), nullable=False, comment='Kỳ này có người trúng Jackpot không'),
    sa.Column('jackpot_value', sa.BigInteger(), nullable=True, comment='Giá trị Jackpot (VND)'),
    sa.Column('raw_html_log', sa.Text(), nullable=True, comment='HTML thô dự phòng'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_results_draw_date'), 'draw_results', ['draw_date'], unique=False)
    op.create_index(op.f('ix_draw_results_draw_period'), 'draw_results', ['draw_period'], unique=True)
    op.create_index(op.f('ix_draw_results_type'), 'draw_results', ['type'], unique=False)
    op.create_table('number_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('max_gap', sa.Integer(), nullable=False, comment='Khoảng cách lớn nhất từng ghi nhận (kỳ)'),
    sa.Column('current_gap', sa.Integer(), nullable=False, comment='Khoảng cách hiện tại tính từ lần cuối xuất hiện (kỳ)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_number_stats_number'), 'number_stats', ['number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FREE', 'PREMIUM', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_numbers', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_number_stats_number'), table_name='number_stats')
    op.drop_table('number_stats')
    op.drop_index(op.f('ix_draw_results_type'), table_name='draw_results')
    op.drop_index(op.f('ix_draw_results_draw_period'), table_name='draw_results')
    op.drop_index(op.f('ix_draw_results_draw_date'), table_name='draw_results')
    op.drop_table('draw_results')
    op.drop_index(op.f('ix_ai_predictions_target_period'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    # ### end Alembic commands ###
